### ISSUE TITLE
Sirius Delegation Support

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-client#109]
**Task description**

The concordium-client application will need to support the new transactions for configure delegation ‘delegator configure' and configure baker ‘baker configure’. They will be similar to the old ‘baker add’ command, but where the arguments are optional for configure.

The old ‘baker add', ‘baker remove', ‘baker set-key’, etc. commands will be changed to use ‘baker configure’ behind the scenes.

The concordium-client will also get new commands ‘delegator add’ and ‘delegator remove’, to add or remove a delegator. These commands will be wrappers around the 'delegator configure’ command.

**Comment by abizjak** [comment]
This is done.
