### ISSUE TITLE
the client gets an error when trying to use an external host.

### ISSUE THREAD

**Issue by pablozsc** [Concordium/concordium-client#110]
**Bug Description**
When trying to use an external host by specifying the grpc port and ip flags, the client gets an error 
Although, the command to view account information is successful.

**Steps to Reproduce**
1. It is enough just to execute the command
`concordium-client consensus show-parameters --include-bakers --grpc-ip 144.76.29.116 --grpc-port 10000`
or this
`concordium-client block show some_block_hash --grpc-ip 144.76.29.116 --grpc-port 10000`

2. As I said above, however, we can successfully execute the command to view account information
`concordium-client account show some_address --grpc-ip 144.76.29.116 --grpc-port 10000`

**Expected Result**
Successful command execution

**Actual Result**
Error: I/O error: gRPC error: not enough bytes.

**Versions**
testing was carried out on concordiumclient version 3.0.4-0
But also happens on earlier versions of the client.

- Software Version 
- OS Windows, Ubuntu (i am sure macos has the same)
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
The reason for this is that the virtual hive node (which is the one you are querying) does not enable all endpoints. It enables those that are relevant for the desktop wallet.

I am closing this since it is not an issue with concordium-client. It is deliberate configuration.

**Comment by pablozsc** [comment]
Thanks for the clarification. @abizjak
