### ISSUE TITLE
Create way for user to check baker staking threshold

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium-client#111]
**Description**
There needs to be an easier way than running a block summary (and digging through that) for a user to find out what the threshold is to become a baker.

When this is made, this issue can be implemented in the documentation: https://github.com/Concordium/concordium.github.io/issues/399

**Comment by abizjak** [comment]
A subcommand of consensus should be added to display all chain parameters.

There is currently show-parameters already, but it only shows election difficulty. All chain parameters (all the ones listed in the block summary) should be shown.

**Comment by dg-concordium** [comment]
You are welcome to link this to #55 or move the information about the documentation issue to 55 and close this issue. As long as the comment about the documentation that needs to be updated is part of 55 so it gets updated when that issue is done, that's fine with me.
