### ISSUE TITLE
Not all accounts listed

### ISSUE THREAD

**Issue by sderuiter** [Concordium/concordium-client#113]
**Bug Description**
When executing the command `concordium-client account list `, a list of accounts is displayed. 3kKn2kz9YHrkrKUcBZF9NUJbg8LqGzcBbLwzH1VPBdK8hmNqCD Is not in this list, however it is a valid account (https://concordium-explorer.nl/account/3kKn2kz9YHrkrKUcBZF9NUJbg8LqGzcBbLwzH1VPBdK8hmNqCD )

**Steps to Reproduce**
Do steps above 
**Expected Result**
Account in list

**Actual Result**
Account not in list. 

**Versions**
- 
- MacOS Monterey 12.1
- 
-

**Comment by abizjak** [comment]
I see that you closed this. Did you realize what was the matter? Could you share here why?

**Comment by sderuiter** [comment]
Hi, I realized too late that there is a concept of aliases (as described here: https://developer.concordium.software/en/mainnet/net/references/transactions.html#account-aliases ). Only the canonical account is reported through Concordium-client. I think you can find aliases by looking at the first 29 bytes of an address if they match, it’s an alias. Correct?

**Comment by abizjak** [comment]
Yes, that is correct.
