### ISSUE TITLE
Register as baker with `baker add` and `baker configure` fails

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-client#114]
**Bug Description**
Trying to register as baker. I used `baker generate-keys` and then `baker add` but it is rejected  with
`Warning: Proof that baker owns relevant private keys is not valid.`

Full command was:
`baker add stagenet10-baker-keys.json --sender "stagenet10" --stake 14000 --open-delegation-for none --delegation-transaction-fee-commission 5.0e-2 --delegation-baking-commission 5.0e-2 --delegation-finalization-commission 1.0 --baker-url baker-url.json --out stagenet10-baker-credentials.json`

**Steps to Reproduce**
- `baker generate-keys` 
- `baker add` 
according to documentation + client help that parameters are missing.

**Expected Result**
Transaction successful.

**Actual Result**
Transaction rejected with `Warning: Proof that baker owns relevant private keys is not valid.`

**Versions**
- concordium-client_4.0.0-delegation-test-0
- Windows

**Comment by concordium-cl** [comment]
TY: "Most likely a bug in the checking or proof generation. One or the other is probably using the wrong challenge."

**Comment by concordium-cl** [comment]
Same with `baker configure`:
`baker configure --keys-in stagenet10-baker-keys-2.json --sender "stagenet10" --stake 14000 --open-delegation-for none --delegation-transaction-fee-commission 5.0e-2 --delegation-baking-commission 5.0e-2 --delegation-finalization-commission 1.0 --baker-url baker-url.json --keys-out stagenet10-baker-credentials-2.json`

**Comment by abizjak** [comment]
Addressed in 4.0.1.
