### ISSUE TITLE
 More info for wrong commission ranges for `baker configure`   

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-client#119]
**Bug Description**
Currently, when one commission is missing, the `baker configure` transaction only shows
`Warning: A commission fee was not within the allowed range.`

**Expected Result**
It should give more specific user guidance on which one exactly.

**Actual Result**
`Warning: A commission fee was not within the allowed range.`

**Versions**
- concordium-client_4.0.0-delegation-test-1
- Windows

**Comment by abizjak** [comment]
Addressed in 4.0.1.
