### ISSUE TITLE
baker update-delegation-status all fails

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-client#120]
**Bug Description**
`Concordium client baker update-delegation-status all` fails with feedback Invalid argument 'all'.

**Expected Result**
Command should open pool for all delegators.

**Actual Result**
Invalid argument 'all'.

**Versions**
- Software Version: Node 4.0.5-delegation-test-1

**Comment by abizjak** [comment]
Addressed in 4.0.1.
