### ISSUE TITLE
Client always set restake to true unless `--no-restake` flag is provided

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-client#122]
**Bug Description**
Client always assumes that restake is true unless user specifically doesn't provide `--no-restake` flag in every command.

**Steps to Reproduce**
Set the stake with flag `--no-restake` so that rewards are not restaked.
Send another command to increase the stake but don't provide a flag for restaking.

**Expected Result**
Stake should be increased and rewards should not be restaked.

**Actual Result**
Stake was increased but rewards are restaked.

**Versions**
- Software Version: concordium-client_4.0.0-delegation-test-1

**Comment by abizjak** [comment]
Addressed in 4.0.1.
