### ISSUE TITLE
`baker update-delegation-status` does not work as described in documentation

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-client#124]
**Bug Description**
Documentation says that syntax is `baker update-delegation-status SELECTION` with `SELECTION = all, existing, none`. However, this does not seem to work.

**Expected Result**
Command works according to documentation, e.g. `baker update-delegation-status all --sender "x"`

**Actual Result**
Invalid argument 

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

**Comment by concordium-cl** [comment]
<img width="1164" alt="delegation3" src="https://user-images.githubusercontent.com/69570978/160614876-5f4eab45-9814-4ea2-80d6-79a344d83c4e.PNG">

**Comment by abizjak** [comment]
Addressed in 4.0.1.
