### ISSUE TITLE
`baker configure --stake 0` does not work

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-client#126]
**Bug Description**
`baker configure --sender "x" --stake 0` is rejected with `Warning: Remove baker failed because of unexpected parameters.`

Note that extensive warning is dealt with in [#121](https://github.com/Concordium/concordium-client/issues/121)
**Expected Result**
`baker configure --stake 0` works as `baker remove`

**Actual Result**
Rejected with unexpected parameters.

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

**Comment by concordium-cl** [comment]
<img width="885" alt="delegation6" src="https://user-images.githubusercontent.com/69570978/160621886-6d114b85-028c-488f-a049-d22f508338bf.PNG">

**Comment by concordium-cl** [comment]
Same issue for `delegator configure --stake 0`; 
`Warning: Remove delegator failed because of unexpected parameters`

**Comment by abizjak** [comment]
Addressed in 4.0.1.
