### ISSUE TITLE
Too much info for delegation commands

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-client#127]
**Bug Description**
For all delegation commands, i.e. `delegator add, remove, configure` there is an unusual amount of info given when submitting and finalizing transactions. It clutters the concordium-client and is not in line with other client commands.

<img width="905" alt="delegting6" src="https://user-images.githubusercontent.com/69570978/161016419-768ff582-af1d-4c42-9459-585c849d139a.PNG">

**Expected Result**
```
Transaction is committed into block ...
[timestamp] Waiting ...
Transaction is finalized into block ...
```

**Actual Result**
```
Transaction is committed into block ...
delegator added
delegator restake earnings ... 
delegator delegation target ... 
[timestamp] Waiting ...
Transaction is finalized into block ...
```

See screenshot.

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

**Comment by abizjak** [comment]
Addressed in 4.0.1.
