### ISSUE TITLE
The help message for `raw GetBakerList` is wrong

### ISSUE THREAD

**Issue by rimbi** [Concordium/concordium-client#128]
**Bug Description**
The help message for `raw GetBakerList` is wrong as follows:
`Query the gRPC server for the status of a baker pool or the L-pool.`

**Steps to Reproduce**
Type `concordium-client raw GetBakerList --help`

**Expected Result**
`Query the gRPC server for the list of bakers`

**Actual Result**
`Query the gRPC server for the status of a baker pool or the L-pool.`

**Versions**
- Software Version: `concordium-client_4.0.0-delegation-test-1`
- OS: MacOS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
Addressed in 4.0.1.
