### ISSUE TITLE
More user friendly feedback for `concordium client raw GetPoolStatus --pool nonExistingId`

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-client#129]
**Bug Description**
Querying node for the pool that doesn't exist with `concordium client raw GetPoolStatus --pool nonExistingId` returns _null_
It would be desirable to have a feedback such as _The pool with the id doesn't exist_ or something similar.

**Steps to Reproduce**
 `concordium client raw GetPoolStatus --pool nonExistingId` 

**Expected Result**
_The pool with the id doesn't exist_ or something similar.

**Actual Result**
_null_

**Versions**
- Software Version: concordium-client_4.0.0-delegation-test-1

**Comment by abizjak** [comment]
I don't think this should be done. The `raw` commands are meant to just return the value directly and are mainly used when the high-level, user friendly commands do not exist. They are also useful for testing and any scripting.

The correct thing would be to provide a high-level command like we have for `consensus show --include-bakers`.

**Comment by mh-concordium** [comment]
Agree.
