### ISSUE TITLE
Attempt to delegate returns Error: Cannot convert 'Object

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-client#133]
**Bug Description**
Attempt to be the owner of pool 118  and at the same time delegate do pool 1 returns Error: Cannot convert 'Object.

**Steps to Reproduce**
Become a baker client.
Use the same account as baker in attempt to delegate to another pool while already being a baker.

**Expected Result**
Transaction failed.

**Actual Result**
Error: Cannot convert 'Object

**Versions**
- Software Version: concordium-client_4.0.0-delegation-test-1

**Comment by abizjak** [comment]
Is there a reason you are not using 4.0.1 version?

That fixes a number of issues and is compatible with the current node.

**Comment by mh-concordium** [comment]
You are right. I was using the old version. Feedback is ok.

![image](https://user-images.githubusercontent.com/98821384/166195064-c5f19185-5b93-4606-b2b8-35a3b10d3222.png)
