### ISSUE TITLE
Migrate client to use GRPC V2

### ISSUE THREAD

**Issue by vikt0r0** [Concordium/concordium-client#197]
### Purpose
The client currently interacts with the V1 GRPC API exposed by the node. Migrating it to use the V2 GRPC API has a number of advantages, including, but perhaps not limited to better types and payload deserialization using code generated from protocol buffer schemas.

### Feature proposal
Due to differences in the V2 GRPC API, changes to the client module API may be introduced. Such changes will be documented in a feature proposal.

### Changes
- [x] Add bootstrapping to generate code from the V2 API protocol buffer schema (in `Setup.hs`).
- [x] Migrate GRPC call helpers to use the V2 GRPC API:
- Add functional "inverse" to the `ToProto` class (i.e. `FromProto`), allowing for conversion between datatypes generated from protocol buffer schemas and their corresponding datatype in (e.g. those in `Concordium.Types.*`, `Concordium.Common`) where applicable. These are not necessarily one-to-one, so checks should be added accordingly.
- (Maybe) refactor `ToProto` and `FromProto` class and instance declarations to `concordium-base`.
- Implement V2 GRPC API calls.
- Rewrite/refactor client functions and helpers to use V2 GRPC API
- Add tests for V2 GRPC API calls

**Comment by abizjak** [comment]
This is completed now and 5.1.0 is released.
