### ISSUE TITLE
Fix the misleading help for raw Shutdown command

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-client#239]
**Bug Description**
Looking at help for `raw Shutdown`, it explains: Shutdown the node gracefully.

**Steps to Reproduce**
`concordium-client raw Shutdown --help`

**Expected Result**
Something related to as node api stops network layer because that's what happens.

**Actual Result**
Help is misleading:
`  Shutdown the node gracefully.
`
**Versions**
- Software Version: 5.1.0

**Comment by abizjak** [comment]
Closed by https://github.com/Concordium/concordium-client/pull/240
