### ISSUE TITLE
Unit "ms" is not shown after the value for chain parameter `minimum time between blocks`

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-client#266]
**Bug Description**
Minimum time between blocks is shown in milliseconds but the client doesn't show "ms" unit after the value.

**Steps to Reproduce**
`concordium-client --grpc-port 20002 consensus show-chain-parameters
`
**Expected Result**
```
# Consensus parameters:
  + Timeout parameters:
     * base timeout: 10000 ms.
     * timeout increase: 5 / 4 (approx 1.25)
     * timeout decrease: 3 / 4 (approx 0.75)
  + minimum time between blocks: 1000 ms.
```

**Actual Result**
```
# Consensus parameters:
  + Timeout parameters:
     * base timeout: 10000 ms.
     * timeout increase: 5 / 4 (approx 1.25)
     * timeout decrease: 3 / 4 (approx 0.75)
  + minimum time between blocks: 1000
```
**Versions**
- Software Version: 6.0.0

**Comment by abizjak** [comment]
This is already fixed by this PR https://github.com/Concordium/concordium-client/pull/265

Will be part of 6.0.1

**Comment by abizjak** [comment]
Closing this since it is part of 6.0.1 release.
