### ISSUE TITLE
Tokenomics changes

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium-client#281]
Renaming of "benign" references to baking/bakers to validation, producing blocks, validator. Remove references to finalization and finalization commission. Baker rewards are now block rewards. Etc.

**Comment by abizjak** [comment]
I think this was completed, apart from removing mentions of finalization commission. I think this needs to stay since concordium-client is a low-level tool that must expose these details which remain in the protocol.

**Comment by abizjak** [comment]
Closing this since version 6.2.1 of the client should now have everything renamed.
