### ISSUE TITLE
Multi-sig signing of ContractUpdate transactions

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-client#296]
**Task description**

Concordium has support for native multi-sig accounts. The goal is to make this feature easily accessible. In particular, person A should be able to sign (not sign and send) a transaction with `concordium-client` and person B should be able to append/pass-in its own signature when signing_and_sending a transaction on-chain.

Using the multi-sig accounts feature via SDK is currently possible (a bit hacky):
https://gist.github.com/DOBEN/683fe1a7c82a0551546a7ec242d30cc0

Related to:
https://github.com/Concordium/concordium-client/issues/38

**Comment by DOBEN** [comment]
I suggest adding an optional ``--no-submit`` flag to toggle between sending or NOT sending the transaction on-chain:
```
concordium-client contract update --signers 0:1,0:2,0:3 --tx-out output.bin/json --no-submit
```

Alternativly, adding a new `sign` command to all transaction types that will NOT send the transaction on-chain would also work:

```
concordium-client contract sign --signers 0:1,0:2,0:3 --tx-out output.bin/json
```

The remaing flow would be:
Adding additional signatures with
```
concordium-client transaction add-signature output.bin --signer 0:2 --tx-out signed-tx.bin/signed-tx.json
```

Submitting the fully signed transaction on chain:
```
```
concordium-client transaction submit signed-tx.bin
```

**Comment by abizjak** [comment]
So the issue is that you will then need multiple "sign" commands, because the transactions are not all under the "transaction" command, e.g., contract updates are under contract, baker stuff is under baker. I don't think this is a good solution.

We already have almost all the options with the existing commands, so it's better to refine it. It'll also be much more straightforward to implement because all "transaction" command share the same command line parser and options.

**Comment by DOBEN** [comment]
The introduction of the `sign` command was an alternative solution to avoid using an extra ` --no-submit` flag but it would mean a lot more code (since we need to add an extra subcommand `sign` for every type of transaction that we have). To simplify the task, let's go with the ``--no-submit`` flag:

The current flow would be:

***Step 1:***

Signig the transaction but not sending it on-chain
```
concordium-client contract update --signers 0:1,0:2,0:3 --tx-out output.bin/json --no-submit
```

***Step 2:***

Adding additional signatures with
```
concordium-client transaction add-signature output.bin --signer 0:2 --tx-out signed-tx.bin/signed-tx.json
```

***Step 3:***

Submitting the fully signed transaction on-chain:
```
concordium-client transaction submit signed-tx.bin
```

**Comment by DOBEN** [comment]
closing since it is implemented now
