### ISSUE TITLE
Support for distributed signing in concordium-client

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-client#38]
At the moment concordium-client can only send transactions where it signs it with all the necessary keys. As it stands, this negates almost all of the benefits of having multiple signatures.

We should also support the client signing a transaction partially so that keys can be shared on different devices, and a transaction signed on different, independent, devices.

A simple solution can be to simply output a partially signed transaction, and be able to read such a transaction in and attach an additional signature, and send it to the node. The format would ideally be compatible with the desktop wallet proposal format.

**Comment by DOBEN** [comment]
closing in https://github.com/Concordium/concordium-client/pull/300

Note: The partially-signed transaction file as generated by the Desktop wallet is currently NOT compatible with file generated by the ``concordium-client`` tool. This can be addressed at a later point.
