### ISSUE TITLE
Warnings with random characters in front of type for baker update-stake

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-client#78]
**Bug Description**
Strange warnings in client when restaking as baker:

![strange_warning](https://user-images.githubusercontent.com/69570978/134313029-241b394e-fdc2-4a73-8d2a-e40e1d2650d3.JPG)

**Steps to Reproduce**
- `baker update-stake`

**Expected Result**
Warnings without characters in front of type.

**Actual Result**
See screenshot.

**Versions**
- Client 1.1.1-0
- Windows node 1.1.2

**Comment by abizjak** [comment]
It would be useful to know what terminal you are using.

These are ANSI codes to color the output, so I'm wondering why they are not correctly interpreted by your system.

**Comment by concordium-cl** [comment]
ConEmu
